// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.clinic.model;

import ar.com.norrmann.clinic.model.Consultorio;
import java.io.Serializable;

privileged aspect Consultorio_Roo_Serializable {
    
    declare parents: Consultorio implements Serializable;
    
    private static final long Consultorio.serialVersionUID = 1L;
    
}
