// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.clinic.model;

import ar.com.norrmann.clinic.model.Dia;

privileged aspect Dia_Roo_JavaBean {
    
    public String Dia.getNombre() {
        return this.nombre;
    }
    
    public void Dia.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
