// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.clinic.model;

import ar.com.norrmann.clinic.model.Profesional;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Profesional_Roo_Configurable {
    
    declare @type: Profesional: @Configurable;
    
}
