// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.norrmann.clinic.model;

import ar.com.norrmann.clinic.model.Profesional;
import java.io.Serializable;

privileged aspect Profesional_Roo_Serializable {
    
    declare parents: Profesional implements Serializable;
    
    private static final long Profesional.serialVersionUID = 1L;
    
}
